import { ApiResponse } from 'apisauce'
import { Api } from '.'
import { GetReposResult, IReposApi } from '../types'
import { getGeneralApiProblem } from './api-problem'

export const mock = [
  {
    allow_forking: true,
    archive_url: 'https://api.github.com/repos/mobxjs/mobx/{archive_format}{/ref}',
    archived: false,
    assignees_url: 'https://api.github.com/repos/mobxjs/mobx/assignees{/user}',
    blobs_url: 'https://api.github.com/repos/mobxjs/mobx/git/blobs{/sha}',
    branches_url: 'https://api.github.com/repos/mobxjs/mobx/branches{/branch}',
    clone_url: 'https://github.com/mobxjs/mobx.git',
    collaborators_url: 'https://api.github.com/repos/mobxjs/mobx/collaborators{/collaborator}',
    comments_url: 'https://api.github.com/repos/mobxjs/mobx/comments{/number}',
    commits_url: 'https://api.github.com/repos/mobxjs/mobx/commits{/sha}',
    compare_url: 'https://api.github.com/repos/mobxjs/mobx/compare/{base}...{head}',
    contents_url: 'https://api.github.com/repos/mobxjs/mobx/contents/{+path}',
    contributors_url: 'https://api.github.com/repos/mobxjs/mobx/contributors',
    created_at: '2015-03-14T14:31:38Z',
    default_branch: 'main',
    deployments_url: 'https://api.github.com/repos/mobxjs/mobx/deployments',
    description: 'Simple, scalable state management.',
    disabled: false,
    downloads_url: 'https://api.github.com/repos/mobxjs/mobx/downloads',
    events_url: 'https://api.github.com/repos/mobxjs/mobx/events',
    fork: false,
    forks: 1708,
    forks_count: 1708,
    forks_url: 'https://api.github.com/repos/mobxjs/mobx/forks',
    full_name: 'mobxjs/mobx',
    git_commits_url: 'https://api.github.com/repos/mobxjs/mobx/git/commits{/sha}',
    git_refs_url: 'https://api.github.com/repos/mobxjs/mobx/git/refs{/sha}',
    git_tags_url: 'https://api.github.com/repos/mobxjs/mobx/git/tags{/sha}',
    git_url: 'git://github.com/mobxjs/mobx.git',
    has_downloads: true,
    has_issues: true,
    has_pages: true,
    has_projects: false,
    has_wiki: true,
    homepage: 'http://mobx.js.org',
    hooks_url: 'https://api.github.com/repos/mobxjs/mobx/hooks',
    html_url: 'https://github.com/mobxjs/mobx',
    id: 32215970,
    is_template: false,
    issue_comment_url: 'https://api.github.com/repos/mobxjs/mobx/issues/comments{/number}',
    issue_events_url: 'https://api.github.com/repos/mobxjs/mobx/issues/events{/number}',
    issues_url: 'https://api.github.com/repos/mobxjs/mobx/issues{/number}',
    keys_url: 'https://api.github.com/repos/mobxjs/mobx/keys{/key_id}',
    labels_url: 'https://api.github.com/repos/mobxjs/mobx/labels{/name}',
    language: 'TypeScript',
    languages_url: 'https://api.github.com/repos/mobxjs/mobx/languages',
    license: {
      key: 'mit',
      name: 'MIT License',
      node_id: 'MDc6TGljZW5zZTEz',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
    },
    merges_url: 'https://api.github.com/repos/mobxjs/mobx/merges',
    milestones_url: 'https://api.github.com/repos/mobxjs/mobx/milestones{/number}',
    mirror_url: null,
    name: 'mobx',
    node_id: 'MDEwOlJlcG9zaXRvcnkzMjIxNTk3MA==',
    notifications_url:
      'https://api.github.com/repos/mobxjs/mobx/notifications{?since,all,participating}',
    open_issues: 21,
    open_issues_count: 21,
    owner: {
      avatar_url: 'https://avatars.githubusercontent.com/u/47021926?v=4',
      events_url: 'https://api.github.com/users/mobxjs/events{/privacy}',
      followers_url: 'https://api.github.com/users/mobxjs/followers',
      following_url: 'https://api.github.com/users/mobxjs/following{/other_user}',
      gists_url: 'https://api.github.com/users/mobxjs/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/mobxjs',
      id: 17475736,
      login: 'mobxjs',
      node_id: 'MDEyOk9yZ2FuaXphdGlvbjE3NDc1NzM2',
      organizations_url: 'https://api.github.com/users/mobxjs/orgs',
      received_events_url: 'https://api.github.com/users/mobxjs/received_events',
      repos_url: 'https://api.github.com/users/mobxjs/repos',
      site_admin: false,
      starred_url: 'https://api.github.com/users/mobxjs/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/mobxjs/subscriptions',
      type: 'Organization',
      url: 'https://api.github.com/users/mobxjs',
    },
    private: false,
    pulls_url: 'https://api.github.com/repos/mobxjs/mobx/pulls{/number}',
    pushed_at: '2022-09-07T17:51:21Z',
    releases_url: 'https://api.github.com/repos/mobxjs/mobx/releases{/id}',
    score: 1,
    size: 18675,
    ssh_url: 'git@github.com:mobxjs/mobx.git',
    stargazers_count: 25686,
    stargazers_url: 'https://api.github.com/repos/mobxjs/mobx/stargazers',
    statuses_url: 'https://api.github.com/repos/mobxjs/mobx/statuses/{sha}',
    subscribers_url: 'https://api.github.com/repos/mobxjs/mobx/subscribers',
    subscription_url: 'https://api.github.com/repos/mobxjs/mobx/subscription',
    svn_url: 'https://github.com/mobxjs/mobx',
    tags_url: 'https://api.github.com/repos/mobxjs/mobx/tags',
    teams_url: 'https://api.github.com/repos/mobxjs/mobx/teams',
    topics: ['javascript', 'mobx', 'react', 'reactive-programming', 'typescript'],
    trees_url: 'https://api.github.com/repos/mobxjs/mobx/git/trees{/sha}',
    updated_at: '2022-09-18T12:44:40Z',
    url: 'https://api.github.com/repos/mobxjs/mobx',
    visibility: 'public',
    watchers: 25686,
    watchers_count: 25686,
    web_commit_signoff_required: false,
  },
  {
    allow_forking: true,
    archive_url: 'https://api.github.com/repos/mobxjs/mobx-react/{archive_format}{/ref}',
    archived: true,
    assignees_url: 'https://api.github.com/repos/mobxjs/mobx-react/assignees{/user}',
    blobs_url: 'https://api.github.com/repos/mobxjs/mobx-react/git/blobs{/sha}',
    branches_url: 'https://api.github.com/repos/mobxjs/mobx-react/branches{/branch}',
    clone_url: 'https://github.com/mobxjs/mobx-react.git',
    collaborators_url:
      'https://api.github.com/repos/mobxjs/mobx-react/collaborators{/collaborator}',
    comments_url: 'https://api.github.com/repos/mobxjs/mobx-react/comments{/number}',
    commits_url: 'https://api.github.com/repos/mobxjs/mobx-react/commits{/sha}',
    compare_url: 'https://api.github.com/repos/mobxjs/mobx-react/compare/{base}...{head}',
    contents_url: 'https://api.github.com/repos/mobxjs/mobx-react/contents/{+path}',
    contributors_url: 'https://api.github.com/repos/mobxjs/mobx-react/contributors',
    created_at: '2015-08-28T11:09:05Z',
    default_branch: 'master',
    deployments_url: 'https://api.github.com/repos/mobxjs/mobx-react/deployments',
    description: 'React bindings for MobX',
    disabled: false,
    downloads_url: 'https://api.github.com/repos/mobxjs/mobx-react/downloads',
    events_url: 'https://api.github.com/repos/mobxjs/mobx-react/events',
    fork: false,
    forks: 375,
    forks_count: 375,
    forks_url: 'https://api.github.com/repos/mobxjs/mobx-react/forks',
    full_name: 'mobxjs/mobx-react',
    git_commits_url: 'https://api.github.com/repos/mobxjs/mobx-react/git/commits{/sha}',
    git_refs_url: 'https://api.github.com/repos/mobxjs/mobx-react/git/refs{/sha}',
    git_tags_url: 'https://api.github.com/repos/mobxjs/mobx-react/git/tags{/sha}',
    git_url: 'git://github.com/mobxjs/mobx-react.git',
    has_downloads: true,
    has_issues: true,
    has_pages: false,
    has_projects: false,
    has_wiki: false,
    homepage: 'https://mobx.js.org/react-integration.html',
    hooks_url: 'https://api.github.com/repos/mobxjs/mobx-react/hooks',
    html_url: 'https://github.com/mobxjs/mobx-react',
    id: 41543133,
    is_template: false,
    issue_comment_url: 'https://api.github.com/repos/mobxjs/mobx-react/issues/comments{/number}',
    issue_events_url: 'https://api.github.com/repos/mobxjs/mobx-react/issues/events{/number}',
    issues_url: 'https://api.github.com/repos/mobxjs/mobx-react/issues{/number}',
    keys_url: 'https://api.github.com/repos/mobxjs/mobx-react/keys{/key_id}',
    labels_url: 'https://api.github.com/repos/mobxjs/mobx-react/labels{/name}',
    language: 'TypeScript',
    languages_url: 'https://api.github.com/repos/mobxjs/mobx-react/languages',
    license: {
      key: 'mit',
      name: 'MIT License',
      node_id: 'MDc6TGljZW5zZTEz',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
    },
    merges_url: 'https://api.github.com/repos/mobxjs/mobx-react/merges',
    milestones_url: 'https://api.github.com/repos/mobxjs/mobx-react/milestones{/number}',
    mirror_url: null,
    name: 'mobx-react',
    node_id: 'MDEwOlJlcG9zaXRvcnk0MTU0MzEzMw==',
    notifications_url:
      'https://api.github.com/repos/mobxjs/mobx-react/notifications{?since,all,participating}',
    open_issues: 0,
    open_issues_count: 0,
    owner: {
      avatar_url: 'https://avatars.githubusercontent.com/u/17475736?v=4',
      events_url: 'https://api.github.com/users/mobxjs/events{/privacy}',
      followers_url: 'https://api.github.com/users/mobxjs/followers',
      following_url: 'https://api.github.com/users/mobxjs/following{/other_user}',
      gists_url: 'https://api.github.com/users/mobxjs/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/mobxjs',
      id: 17475736,
      login: 'mobxjs',
      node_id: 'MDEyOk9yZ2FuaXphdGlvbjE3NDc1NzM2',
      organizations_url: 'https://api.github.com/users/mobxjs/orgs',
      received_events_url: 'https://api.github.com/users/mobxjs/received_events',
      repos_url: 'https://api.github.com/users/mobxjs/repos',
      site_admin: false,
      starred_url: 'https://api.github.com/users/mobxjs/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/mobxjs/subscriptions',
      type: 'Organization',
      url: 'https://api.github.com/users/mobxjs',
    },
    private: false,
    pulls_url: 'https://api.github.com/repos/mobxjs/mobx-react/pulls{/number}',
    pushed_at: '2020-12-30T16:19:32Z',
    releases_url: 'https://api.github.com/repos/mobxjs/mobx-react/releases{/id}',
    score: 1,
    size: 2388,
    ssh_url: 'git@github.com:mobxjs/mobx-react.git',
    stargazers_count: 4852,
    stargazers_url: 'https://api.github.com/repos/mobxjs/mobx-react/stargazers',
    statuses_url: 'https://api.github.com/repos/mobxjs/mobx-react/statuses/{sha}',
    subscribers_url: 'https://api.github.com/repos/mobxjs/mobx-react/subscribers',
    subscription_url: 'https://api.github.com/repos/mobxjs/mobx-react/subscription',
    svn_url: 'https://github.com/mobxjs/mobx-react',
    tags_url: 'https://api.github.com/repos/mobxjs/mobx-react/tags',
    teams_url: 'https://api.github.com/repos/mobxjs/mobx-react/teams',
    topics: ['javascript', 'mobx', 'react', 'react-components', 'reactive-programming'],
    trees_url: 'https://api.github.com/repos/mobxjs/mobx-react/git/trees{/sha}',
    updated_at: '2022-09-17T14:15:08Z',
    url: 'https://api.github.com/repos/mobxjs/mobx-react',
    visibility: 'public',
    watchers: 4852,
    watchers_count: 4852,
    web_commit_signoff_required: false,
  },
]

class RepoApi {
  async getRepos(searchText: string, page: number, perPage?: number): Promise<GetReposResult> {
    try {
      const response: ApiResponse<IReposApi> = await Api.apisauce.get('/search/repositories', {
        q: searchText,
        page,
        per_page: perPage,
      })

      if (!response.ok) {
        const problem = getGeneralApiProblem(response)
        console.log('TEST problem', problem)
        if (problem) {
          throw problem
        }
      }

      // console.log('TEST response 0', response.data.items[0])
      // console.log('TEST response 1', response.data.items[1])

      return { kind: 'ok', repos: response?.data?.items, total: response?.data?.total_count }
      // return { kind: 'ok', repos: mock, total: 2 }
    } catch (e) {
      throw Error(e.kind)
    }
  }
}

export default new RepoApi()
