export const icons = {
  search: require('./search.png'),
  heart: require('./heart.png'),
  heartRed: require('./heart-red.png'),
  home: require('./home-38.png'),
  conversation: require('./conversation-39.png'),
  friends: require('./add-group-38.png'),
  dollar: require('./dollar-37.png'),
  dot: require('./Ellipse-405.png'),
  defaultUserImage: require('./default-user-image.png'),
  imageView: require('./image-view-1.png'),
  addImage: require('./add-image.png'),
}
export enum Icons {
  SEARCH = 'search',
  HEART = 'heart',
  HEART_RED = 'heartRed',
  HOME = 'home',
  CONVERSATION = 'conversation',
  FRIENDS = 'friends',
  DOLLAR = 'dollar',
  DOT = 'dot',
  DEFAULT_USER_IMAGE = 'defaultUserImage',
  IMAGE_VIEW = 'imageView',
  ADD_IMAGE = 'addImage',
}
